# Generated by Django 2.1 on 2018-08-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FridayGames',
            new_name='FridayGame',
        ),
    ]
