# Generated by Django 2.1 on 2018-08-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0002_auto_20180820_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaturdayGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('team1', models.CharField(max_length=64)),
                ('team1image', models.CharField(max_length=64)),
                ('team2', models.CharField(max_length=64)),
                ('team2image', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
                ('network_image', models.CharField(max_length=64)),
            ],
        ),
    ]
