# Generated by Django 2.1 on 2018-08-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0005_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='entry_image',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
