# Generated by Django 2.1 on 2018-08-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0006_media_entry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('commment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('week', models.IntegerField()),
            ],
        ),
    ]
