# Generated by Django 2.1 on 2018-08-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commment',
            new_name='comment',
        ),
    ]
