# Generated by Django 2.1 on 2018-08-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_prices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prices',
            new_name='Price',
        ),
    ]
