# Generated by Django 2.1 on 2018-08-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_auto_20180829_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('SP', 'Specialty Pizza'), ('RG', 'Create Your Own Pizza')], default='SP', max_length=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', max_length=64),
        ),
    ]
