# Generated by Django 2.1 on 2018-08-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20180829_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('SP', 'Specialty Pizza'), ('RG', 'Create Your Own Pizza'), ('TP', 'Toppings')], default='SP', max_length=8),
        ),
        migrations.AlterField(
            model_name='specialtypizza',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
