# Generated by Django 2.1 on 2018-08-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_auto_20180830_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('CZ', 'Calzone'), ('SW', 'Sandwich'), ('SL', 'Salad'), ('AP', 'Appetizer')], default='SW', max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
