# Generated by Django 2.1 on 2018-08-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_otheritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheritem',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
