# Generated by Django 2.1 on 2018-08-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0013_auto_20180830_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X-Large', 'Extra Large')], default='Small', max_length=64),
        ),
    ]
