# Generated by Django 2.1 on 2018-09-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0017_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
