# Generated by Django 2.1 on 2018-09-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0019_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtySizePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='specialtypizza',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='spizza', to='pizza.SpecialtySizePrice'),
        ),
    ]
