# Generated by Django 2.1 on 2018-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0020_auto_20180906_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('topping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toppings', models.ManyToManyField(blank=True, related_name='createpizza', to='pizza.Topping')),
            ],
        ),
        migrations.AlterField(
            model_name='specialtypizza',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='specialtypizza', to='pizza.SpecialtySizePrice'),
        ),
    ]
