# Generated by Django 2.1 on 2018-09-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0021_auto_20180906_1000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
