# Generated by Django 2.1 on 2018-09-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0022_delete_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialtypizza',
            name='size',
        ),
        migrations.AddField(
            model_name='specialtypizza',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialtypizza', to='pizza.SpecialtySizePrice'),
        ),
    ]
