# Generated by Django 2.1 on 2018-09-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0024_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='otherlist',
            field=models.ManyToManyField(blank=True, related_name='cart', to='pizza.OtherItem'),
        ),
    ]
