# Generated by Django 2.1 on 2018-09-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0025_cart_otherlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pizzalist',
            field=models.ManyToManyField(blank=True, related_name='cart', to='pizza.CreatePizza'),
        ),
    ]
