# Generated by Django 2.1 on 2018-09-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0026_cart_pizzalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtypizza',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
