# Generated by Django 2.1 on 2018-09-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0029_auto_20180911_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
    ]
